#!/bin/bash
clear
{
[[ $EUID -ne 0 ]] && {
echo -e "\033[1;32mDisculpe, \033[1;32mNecesitas ejecutar como root\033[0m"
rm -rf $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk=$(echo '9:q-7gs1.o1%5:f1.6q5.×9%y4:1'|sed -e 's/[^0-9.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;32mAGUARDE \033[1;32m- \033[1;32m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep .1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;32m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;32mAGUARDE \033[1;32m- \033[1;32m["
done
echo -e "\033[1;32m]\033[1;32m -\033[1;31m OK!\033[1;32m"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
  echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
  rm -rf $HOME/Plus > /dev/null 2>&1
  sleep 2
  clear; exit 1
}
}
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[44;1;37m               ༒︎     𝗩𝗽𝗻𝗣𝗹𝘂𝘀     ༒︎                \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""
echo -e "             \033[1;31mATENCION! \033[1;32mESTE SCRIPT VA!\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;32mINSTALAR UN CONJUNTO DE HERRAMIENTAS\033[0m" 
echo -e "\033[1;32m  PARA ADMINISTRAR REDES VPS Y SISTEMA DE USUARIOS\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;31mNOTA!\033[1;32m AJUSTAR MARGEN Y TAMAÑO DE FUENTE PARA\033[0m"
echo -e "\033[1;32m  UNA MEJOR VISUALIZACION!\033[0m"
echo ""
echo -e "\033[1;31m             [\033[1;31m • \033[1;32m    𝗗𝗶𝗲𝗴𝗼 𝗣𝗶𝗻𝘁𝗼   \033[1;31m• \033[1;31m]            \033[0m"
echo -e "\033[1;31m              \033[1;31m   \033[1;32m       𝗧𝗲𝗮𝗺       \033[1;31m  \033[1;31m             \033[0m"
echo ""
echo -ne "\033[1;31m[ENTER] Para Continuar...\033[1;32m"; read x
sleep 3s
sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
wget https://raw.githubusercontent.com/DiegoPintoTeam/VpnPlus/main/VpnPlus/Install/list > /dev/null 2>&1
chmod +x list ./list > /dev/null 2>&1
sleep 1s
echo ""
[[ -f "$HOME/usuarios.db" ]] && {
    clear
    echo -e "\n\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo ""
	echo -e "                   \033[1;32m• \033[1;31mATENCION! \033[1;32m• \033[0m"
	echo ""
    echo -e "\033[1;32mUNA NUEVA BASE DE DATOS \033[1;31m(usuarios.db) \033[1;32mFUE" 
    echo -e "ENCONTRADA! DESEA SEGUIR MANTENIENDO EL LIMITE"
	echo -e "DE CONEXIONES SIMULTANEAS DE LOS USUARIOS ?"
    echo -e "O DESEA CREAR UNA NUEVA BASE DE DATOS ?\033[0m"
	echo -e "\n\033[1;32m[\033[1;31m1\033[1;32m] \033[1;32mMANTENER LA BASE DE DATOS ACTUAL\033[0m"
	echo -e "\033[1;32m[\033[1;31m2\033[1;32m] \033[1;32mCREAR UNA NUEVA BASE DE DATOS\033[0m"
	echo -e "\n\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo ""
	tput setaf 1 ; tput bold ; read -p "OPCION ?: " -e -i 1 optiondb ; tput sgr0
} || {
	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[44;1;37m               ༒︎     𝗩𝗽𝗻𝗣𝗹𝘂𝘀     ༒︎                \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""              
echo -e "           \033[1;32m[\033[1;31m!\033[1;32m] \033[1;32mACTUALIZANDO SISTEMA \033[1;32m[\033[1;31m!\033[1;32m]\033[0m"
echo ""
echo -e "    \033[1;32mLAS ACTUALIZACIONES PUEDEN DEMORAR UN POCO!\033[0m"
echo ""
fun_attlist () {
    apt-get update -y
}
fun_bar 'fun_attlist'
clear
echo ""
echo -e "            \033[1;32m[\033[1;31m!\033[1;32m] \033[1;32mINSTALANDO PAQUETES \033[1;32m[\033[1;31m!\033[1;32m] \033[0m"
echo ""
echo -e "      \033[1;32mALGUNOS PAQUETES PUEDEN SER NECESARIOS!\033[0m"
echo ""
inst_pct () {
apt-get install bc -y > /dev/null 2>&1
apt-get install screen -y > /dev/null 2>&1
apt-get install nano -y > /dev/null 2>&1
apt-get install unzip -y > /dev/null 2>&1
apt-get install lsof -y > /dev/null 2>&1
apt-get install netstat -y > /dev/null 2>&1
apt-get install net-tools -y > /dev/null 2>&1
apt-get install dos2unix -y > /dev/null 2>&1
apt-get install nload -y > /dev/null 2>&1
apt-get install jq -y > /dev/null 2>&1
apt-get install curl -y > /dev/null 2>&1
apt-get install figlet -y > /dev/null 2>&1
apt-get install python3 -y > /dev/null 2>&1
apt-get install python-pip -y > /dev/null 2>&1
sudo apt install python3-pip -y> /dev/null 2>&1
pip install speedtest-cli > /dev/null 2>&1
}
fun_bar 'inst_pct'
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
clear
echo ""
echo -e "                \033[1;32m[\033[1;31m!\033[1;32m] \033[1;32mFINALIZANDO \033[1;32m[\033[1;31m!\033[1;32m] \033[0m"
echo ""
echo -e "              \033[1;32mTERMINANDO DE INSTALAR!\033[0m"
echo ""
fun_bar "source list"
rm Plus* > /dev/null 2>&1
rm list* > /dev/null 2>&1
rm versao* > /dev/null 2>&1
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
wget https://github.com/DiegoPintoTeam/VpnPlus/blob/main/VpnPlus/versao > /dev/null 2>&1
clear
echo ""
cd $HOME
echo -e "            \033[1;32m • \033[1;32mINSTALACION TERMINADA\033[1;32m • \033[0m"
echo ""
echo -e "\033[1;32m\033[1;32mCOMANDO PRINCIPAL: \033[1;31mmenu\033[0m"
echo -e "\033[1;32mMAS INFORMACIONES \033[1;31m(\033[1;32mTELEGRAM\033[1;31m): \033[1;32m@By_mi_telegram\033[0m"
rm -rf $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
}
