#!/bin/bash

clear

fun_bar () {

comando[0]="$1"

comando[1]="$2"

 (

[[ -e $HOME/fim ]] && rm $HOME/fim

${comando[0]} > /dev/null 2>&1

${comando[1]} > /dev/null 2>&1

touch $HOME/fim

 ) > /dev/null 2>&1 &

 tput civis

echo -ne "   \033[1;32mAGUARDE \033[1;32m- \033[1;32m["

while true; do

   for((i=0; i<18; i++)); do

   echo -ne "\033[1;31m#"

   sleep .1s

   done

   [[ -e $HOME/fim ]] && rm $HOME/fim && break

   echo -e "\033[1;32m]"

   sleep 1s

   tput cuu1

   tput dl1

   echo -ne "   \033[1;32mAGUARDE \033[1;32m- \033[1;32m["

done

echo -e "\033[1;32m]\033[1;32m -\033[1;32m OK!\033[1;32m"

tput cnorm

}

echo " "

fun_atts () {

  [[ -e /home/versao ]] && rm /home/versao

  [[ -e /tmp/att ]] && rm /tmp/att

	wget -c -P /home https://www.dropbox.com/s/7qt0d3i6ldof9i9/versao

	[[ -f "/home/versao" ]] && mv /home/versao /tmp/att

	[[ ! -e /bin/versao ]] && rm -rf /bin/menu

} > /dev/null 2>&1

echo -e " \033[1;31m                  Diego Pinto \033[1;32m"

echo -e "   VPNPlus" | figlet

echo " "

echo -e "   \033[1;32mVERIFICANDO ACTUALIZACIONES...\033[0m\n"

fun_bar 'fun_atts'

[[ ! -f "/tmp/att" ]] && {

	echo -e "\n\033[1;31mError al conectar con el servidor\n"

	echo -ne "\033[1;31m ENTER \033[1;32mpara volver al \033[1;32mMENU!\033[0m"; read

	menu

}

echo " "

vrs1=$(sed -n '1 p' /bin/versao| sed -e 's/[^0-9]//ig')

vrs2=$(sed -n '1 p' /tmp/att | sed -e 's/[^0-9]//ig')

[[ "$vrs1" == "$vrs2" ]] && {

  echo -e " \033[1;32m     El script ya esta actualizado!\033[1;32m\n"

  rm /tmp/att > /dev/null 2>&1

  echo -e " \033[1;32mMas información \033[1;31m(\033[1;32mTelegram\033[1;31m): \033[1;32m@By_mi_telegram\n"

  echo -ne " \033[1;31m ENTER \033[1;32mpara volver al \033[1;32mMENU!\033[0m"; read

  menu

} || {

  echo -e "  \033[1;32mExiste una nueva actualización!\033[1;32m\n"

  echo -e "  \033[1;32mMas informacion \033[1;31m(\033[1;32mTELEGRAM\033[1;31m): \033[1;32m@By_mi_telegram\n"

  echo -e "  \033[1;32mDetalles de la actualización:\033[0m\n"

  while read linha; do

    echo -e "  \033[1;32m- \033[1;32m$linha"

  done < "/tmp/att"

  echo " "

  echo -ne "  \033[1;32mDesea actualizar [s/n]: "; read res

  if [[ "$res" = s || "$res" = S ]];then

    echo -e "\n\033[1;32mINICIANDO ACTUALIZACIÓN..."

    sleep 3s

    wget https://www.dropbox.com/s/y18ti4w4n1ozb3h/Plus > /dev/null 2>&1

    chmod +x Plus

    ./Plus

    clear

    echo -e "\033[1;32mScript actualizado con exito!\033[0m\n"

    rm /tmp/att > /dev/null 2>&1

    echo -ne "\033[1;31mENTER \033[1;32mpara volver al \033[1;32mMENU!\033[0m"; read

    menu

  else

    menu

  fi

}

