#!/bin/bash
clear
{
echo -e "\E[44;1;37m                INFORMACION DE VPS                \E[0m"
echo ""
if [ -f /etc/lsb-release ]
then
echo -e "\033[1;31m• \033[1;32mSISTEMA OPERATIVO\033[1;31m •\033[0m"
echo ""
name=$(cat /etc/lsb-release |grep DESCRIPCIÓN |awk -F = {'print $2'})
codename=$(cat /etc/lsb-release |grep CODENAME |awk -F = {'print $2'})
echo -e "\033[1;32mNOMBRE: \033[1;31m$name"
echo -e "\033[1;32mCODENAME: \033[1;31m$codename"
echo -e "\033[1;32mKERNEL: \033[1;31m$(uname -s)"
echo -e "\033[1;32mKERNEL RELEASE: \033[1;31m$(uname -r)"
if [ -f /etc/os-release ]
then
devlike=$(cat /etc/os-release |grep LIKE |awk -F = {'print $2'})
echo -e "\033[1;32mINFORMACION DE SO: \033[1;31m$devlike"
echo ""
fi
else
system=$(cat /etc/issue.net)
echo -e "\033[1;31m• \033[1;32mSISTEMA OPERATIVO\033[1;31m •\033[0m"
echo ""
echo -e "\033[1;32mNOMBRE: \033[1;31m$system"
echo ""
fi

if [ -f /proc/cpuinfo ]
then
uso=$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')
echo -e "\033[1;31m• \033[1;32mPROCESADOR\033[1;31m •\033[0m"
echo ""
modelo=$(cat /proc/cpuinfo |grep "model name" |uniq |awk -F : {'print $2'})
cpucores=$(grep -c cpu[0-9] /proc/stat)
cache=$(cat /proc/cpuinfo |grep "cache size" |uniq |awk -F : {'print $2'})
echo -e "\033[1;32mMODELO:\033[1;31m$modelo"
echo -e "\033[1;32mNUCLEOS: \033[1;31m$cpucores"
echo -e "\033[1;32mMEMORIA CACHE:\033[1;31m$cache"
echo -e "\033[1;32mARQUITECTURA: \033[1;31m$(uname -p)"
echo -e "\033[1;32mUTILIZADO: \033[37m$uso"
echo ""
else
echo -e "\033[1;32mPROCESADOR\033[0m"
echo ""
echo "NO SE PUDO OBTENER INFORMACION"
fi

if free 1>/dev/null 2>/dev/null
then
ram1=$(free -h | grep -i mem | awk {'print $2'})
ram2=$(free -h | grep -i mem | awk {'print $4'})
ram3=$(free -h | grep -i mem | awk {'print $3'})
usoram=$(free -m | awk 'NR==2{printf "%.2f%%\t\t", $3*100/$2 }')

echo -e "\033[1;31m• \033[1;32mMEMORIA RAM\033[1;31m •\033[0m"
echo ""
echo -e "\033[1;32mTOTAL: \033[1;31m$ram1"
echo -e "\033[1;32mEN USO: \033[1;31m$ram3"
echo -e "\033[1;32mLIBRE: \033[1;31m$ram2"
echo -e "\033[1;32mUTILIZADO: \033[37m$usoram"
echo ""
else
echo -e "\033[1;32mMEMORIA RAM\033[0m"
echo ""
echo "NO SE PUDO OBTENER INFORMACION"
fi
[[ ! -e /bin/versao ]] && rm -rf /etc/VPNPlus
echo -e "\033[1;31m• \033[1;32mSERVICIOS EN EJECUCION\033[1;31m •\033[0m"
echo ""
PT=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN")
for porta in `echo -e "$PT" | cut -d: -f2 | cut -d' ' -f1 | uniq`; do
    svcs=$(echo -e "$PT" | grep -w "$porta" | awk '{print $1}' | uniq)
    echo -e "\033[1;32mSERVICIO: \033[1;31m$svcs \033[1;32mPUERTO: \033[1;31m$porta"
done
}