#!/bin/bash
clear
{
fun_prog ()
{
	comando[0]="$1" 
    ${comando[0]}  > /dev/null 2>&1 & 
	tput civis
	echo -ne "\033[1;32m.\033[1;32m.\033[1;31m. \033[1;31m"
    while [ -d /proc/$! ]
	do
		for i in / - \\ \|
		do
			sleep .1s
			echo -ne "\e[1D$i"
		done
	done
	tput cnorm
	echo -e "\e[1DOK"
}
echo -ne "\033[1;32mREINICIANDO OPENSSH...\033[0m"; fun_prog 'service ssh restart'
echo ""
sleep .1s
if [[ -e /etc/squid/squid.conf ]]; then
echo -ne "\033[1;32mREINICIANDO SQUID PROXY...\033[0m"; fun_prog 'service squid restart'
echo ""
sleep .1s
elif [[ -e /etc/squid3/squid.conf ]]; then
echo -ne "\033[1;32mREINICIANDO SQUID PROXY...\033[0m"; fun_prog 'service squid3 restart'
echo ""
sleep .1s
fi
if [[ -e /etc/stunnel/stunnel.conf ]]; then
echo -ne "\033[1;32mREINICIANDO SSL TUNNEL...\033[0m"; fun_prog 'service stunnel4 restart'
echo ""
sleep .1s
fi
if [[ -e /etc/init.d/dropbear ]]; then
echo -ne "\033[1;32mREINICIANDO DROPBEAR...\033[0m"; fun_prog 'service dropbear restart'
echo ""
sleep .1s
fi
if [[ -e /etc/openvpn/server.conf ]]; then
echo -ne "\033[1;32mREINICIANDO OPENVPN...\033[0m"; fun_prog 'service openvpn restart'
echo ""
sleep .1s
fi
if netstat -nltp|grep 'apache2' > /dev/null; then
echo -ne "\033[1;32mREINICIANDO APACHE2...\033[0m"; fun_prog '/etc/init.d/apache2 restart'
echo ""
sleep .1s
fi
echo -e "\033[1;31mSERVICIOS REINICIADOS!\033[0m"
sleep .1s
}