#!/bin/bash
clear
{
#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#	SCRIPT: CONEXION <<< VpnPlus >>>
#   DATA ATT:   15 de Jul 2020
#	DESARROLLADO POR:	DIEGO PINTO
#	CONTACTO TELEGRAM:	https://t.me/By_mi_telegram
#	CANAL TELEGRAM:	https://t.me/By_mi_telegram
#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
_lvk=$(wget -qO- https://www.dropbox.com/s/7qt0d3i6ldof9i9/versao)
IP=$(wget -qO- ipv4.icanhazip.com)
IP2=$(wget -qO- http://whatismyip.akamai.com/)
[[ "$IP" != "$IP2" ]] && ipdovps="$IP2" || ipdovps="$IP"
echo -e "$ipdovps" >/etc/IP
echo -e "America/Bogota" >/etc/timezone
ln -fs /usr/share/zoneinfo/America/Bogota /etc/localtime >/dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata >/dev/null 2>&1
[[ ! -d /etc/VPNPlus ]] && mkdir /etc/VPNPlus
[[ ! -d /etc/VPNPlus/senha ]] && mkdir /etc/VPNPlus/senha
[[ ! -e /etc/VPNPlus/Exp ]] && touch /etc/VPNPlus/Exp
[[ ! -d /etc/VPNPlus/userteste ]] && mkdir /etc/VPNPlus/userteste
echo -e 'by: @diego_pinto' > /usr/lib/vpnplus && cat /usr/lib/vpnplus > /usr/lib/licence
netstat -nplt | grep -w 'apache2' | grep -w '80' && sed -i "s/Listen 80/Listen 81/g" /etc/apache2/ports.conf && service apache2 restart
[[ "$(grep -o '#Port 22' /etc/ssh/sshd_config)" == "#Port 22" ]] && sed -i "s;#Port 22;Port 22;" /etc/ssh/sshd_config && service ssh restart
grep -v "^PasswordAuthentication" /etc/ssh/sshd_config >/tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >>/etc/ssh/sshd_config
service ssh restart

wget https://www.dropbox.com/s/n3725c8cctq112s/addhost -O /bin/addhost > /dev/null 2>&1
chmod +x /bin/addhost
wget https://www.dropbox.com/s/j9e62jw0l3a69y0/alterarlimite -O /bin/alterarlimite > /dev/null 2>&1
chmod +x /bin/alterarlimite
wget https://www.dropbox.com/s/pisguwmklbabsum/alterarsenha -O /bin/alterarsenha > /dev/null 2>&1
chmod +x /bin/alterarsenha
wget https://www.dropbox.com/s/kd09dpbavlc1iv4/attscript -O /bin/attscript > /dev/null 2>&1
chmod +x /bin/attscript
wget https://www.dropbox.com/s/kteyzf5daxnyhjw/badvpn -O /bin/badvpn > /dev/null 2>&1
chmod +x /bin/badvpn
wget https://www.dropbox.com/s/u1fworc38rwqrg8/banner -O /bin/banner > /dev/null 2>&1
chmod +x /bin/banner
wget https://www.dropbox.com/s/696uwql46s0dd2e/conexao -O /bin/conexao > /dev/null 2>&1
chmod +x /bin/conexao
wget https://www.dropbox.com/s/6rgphynbz6o22rn/bloquear -O /bin/bloquear > /dev/null 2>&1
chmod +x /bin/bloquear
wget https://www.dropbox.com/s/f6g1iwh1cmsn40c/criarusuario -O /bin/criarusuario > /dev/null 2>&1
chmod +x /bin/criarusuario
wget https://www.dropbox.com/s/dy47nok6uy5jimq/delhost -O /bin/delhost > /dev/null 2>&1
chmod +x /bin/delhost
wget https://www.dropbox.com/s/kxg0wxd5k25px61/delscript -O /bin/delscript > /dev/null 2>&1
chmod +x /bin/delscript
wget https://www.dropbox.com/s/pkyl5c48a5gvhd9/detalhes -O /bin/detalhes > /dev/null 2>&1
chmod +x /bin/detalhes
wget https://www.dropbox.com/s/12vsw9wrcxcdrdo/droplimiter -O /bin/droplimiter > /dev/null 2>&1
chmod +x /bin/droplimiter
wget https://www.dropbox.com/s/u17b8d1hdosmnt6/expcleaner -O /bin/expcleaner > /dev/null 2>&1
chmod +x /bin/expcleaner
wget https://www.dropbox.com/s/yww6dmqcpyygivh/infousers -O /bin/infousers > /dev/null 2>&1
chmod +x /bin/infousers
wget https://www.dropbox.com/s/f4znm7fh88me9zm/limiter -O /bin/limiter > /dev/null 2>&1
chmod +x /bin/limiter
wget https://www.dropbox.com/s/jbhrdjjp14h6apv/menu -O /bin/menu > /dev/null 2>&1
chmod +x /bin/menu
wget https://www.dropbox.com/s/l2zi1npzzl0p5h4/mudardata -O /bin/mudardata > /dev/null 2>&1
chmod +x /bin/mudardata
wget https://www.dropbox.com/s/5sjl6y6inoc3g6g/otimizar -O /bin/otimizar > /dev/null 2>&1
chmod +x /bin/otimizar
wget https://www.dropbox.com/s/arzlyginkaf5ueh/reiniciarservicos -O /bin/reiniciarservicos > /dev/null 2>&1
chmod +x /bin/reiniciarservicos
wget https://www.dropbox.com/s/7g4ahjy4no825dy/reiniciarsistema -O /bin/reiniciarsistema > /dev/null 2>&1
chmod +x /bin/reiniciarsistema
wget https://www.dropbox.com/s/y8p8147inlbf51n/remover -O /bin/remover > /dev/null 2>&1
chmod +x /bin/remover
wget https://www.dropbox.com/s/iarqs4a3vog9zjc/senharoot -O /bin/senharoot > /dev/null 2>&1
chmod +x /bin/senharoot
wget https://www.dropbox.com/s/vl4egza49dyds4o/speedtest -O /bin/speedtest > /dev/null 2>&1
chmod +x /bin/speedtest
wget https://www.dropbox.com/s/vqfyqgpgpspairh/sshmonitor -O /bin/sshmonitor > /dev/null 2>&1
chmod +x /bin/sshmonitor
wget https://www.dropbox.com/s/qex4tqs86198qmu/uexpired -O /bin/uexpired > /dev/null 2>&1
chmod +x /bin/uexpired
wget https://www.dropbox.com/s/4ee9v89hzbtm7pi/userbackup -O /bin/userbackup > /dev/null 2>&1
chmod +x /bin/userbackup
wget https://www.dropbox.com/s/06ofy3ioity10pi/verifatt -O /bin/verifatt > /dev/null 2>&1
chmod +x /bin/verifatt
wget https://www.dropbox.com/s/p0j4zhbih0v5bpb/cabecalho -O /etc/VPNPlus/cabecalho > /dev/null 2>&1
chmod +x /etc/VPNPlus/cabecalho
wget https://www.dropbox.com/s/jrgp87gbtyvvla9/proxy.py -O /etc/VPNPlus/proxy.py > /dev/null 2>&1
chmod +x /etc/VPNPlus/proxy.py
wget https://www.dropbox.com/s/cb0w5xh3k7udem2/open.py -O /etc/VPNPlus/open.py > /dev/null 2>&1
chmod +x /etc/VPNPlus/open.py

_dir1='/bin'
_dir2='/etc/VPNPlus'
_mdls=("addhost" "delhost" "alterarsenha" "criarusuario" "expcleaner" "mudardata" "remover" "bloquear" "droplimiter" "alterarlimite" "sshmonitor" "badvpn" "userbackup" "otimizar" "menu" "speedtest" "banner" "senharoot" "reiniciarservicos" "reiniciarsistema" "attscript" "conexao" "delscript" "detalhes" "infousers" "verifatt" "limiter" "uexpired" "cabecalho" "open.py" "proxy.py")
_arq_host="/etc/hosts"
_host[0]="cloudfront.net"
_host[1]="dns.whatsapp.net"
_host[2]="google.com/recarga"
_host[3]="line.naver.jp/controle/"
_host[4]="www.movistar.com.co/pre/"
_host[5]="www.whatsapp.net"
_host[6]="/VPNPLUS?"
for host in ${_host[@]}; do
	if [[ "$(grep -w "$host" $_arq_host | wc -l)" = "0" ]]; then
		sed -i "3i\127.0.0.1 $host" $_arq_host
	fi
done
[[ ! -e /etc/autostart ]] && {
	echo '#!/bin/bash
clear
#INICIO AUTOMATICO...' >/etc/autostart
	chmod +x /etc/autostart
} || {
	[[ $(ps x | grep -v grep | wc -l) != '0' ]] && wget -qO-
	for proc in $(ps x | grep 'dmS' | grep -v 'grep' | awk {'print $1'}); do
		screen -r -S "$proc" -X quit
	done
	screen -wipe >/dev/null
	echo '#!/bin/bash
clear
#INICIO AUTOMATICO...' >/etc/autostart
	chmod +x /etc/autostart
}
crontab -r >/dev/null 2>&1
(
	crontab -l 2>/dev/null
	echo "@daily /bin/verifatt"
	echo "@reboot /etc/autostart"
	echo "* * * * * /etc/autostart"
	echo "0 */6 * * * /bin/uexpired"
) | crontab -
echo "$_lvk" | sed -n '1 p' | cut -d' ' -f2 >/bin/versao && cat /bin/versao >/home/vpnplus
wget https://www.dropbox.com/s/hjkrvhpqgz377p7/jq-linux64 >/dev/null 2>&1
chmod +x jq-linux64 && mv jq-linux64 $(which jq)
service cron restart >/dev/null 2>&1
service ssh restart >/dev/null 2>&1
[[ -d /var/www/html/openvpn ]] && service apache2 restart >/dev/null 2>&1
rm -rf $home/list >/dev/null 2>&1
}